### ISSUE TITLE
Unable to visit page when using private mode on WebKit browsers

### ISSUE THREAD

**Issue by HenryHins** [serify-health/website#27]
It shows a blank page when using private mode on Safari on Mac and iOS, and Chrome on iOS

**Comment by wparad** [comment]
@HenryHins, any idea what the error message is?

**Comment by HenryHins** [comment]
[Error] QuotaExceededError (DOM Exception 22): The quota has been exceeded.
	setItem (MainHandler.js:1)
	Global Code (MainHandler.js:1)

[Error] XMLHttpRequest cannot load safari-extension://com.evernote.safari.clipper-Q79WDW8YH9/893e5104/_locales/en_us/messages.json. Cross origin requests are only supported for HTTP.

[Error] XMLHttpRequest cannot load safari-extension://com.evernote.safari.clipper-Q79WDW8YH9/893e5104/_locales/en/messages.json. Cross origin requests are only supported for HTTP

[Error] Error: [$injector:modulerr] http://errors.angularjs.org/1.5.8/$injector/modulerr?...

[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403)

[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403)

**Comment by HenryHins** [comment]
Now the nav bar and the footer are showing. But the icon and buttons are gona on the nav bar.

**Comment by wparad** [comment]
This is the relevant error: `Error] Error: [$injector:modulerr] http://errors.angularjs.org/1.5.8/$injector/modulerr?...`  can you click on that link and paste what the error message shows on ttlhe webpage?  Without the additional data, tho current message doesn't help much.

**Comment by HenryHins** [comment]
The link is: https://docs.angularjs.org/error/$injector/modulerr?p0=MainApp&p1=The%20quota%20has%20been%20exceeded.%0AsetItem@%5Bnative%20code%5D%0ASave@https:%2F%2Fserify.org%2FStorageProviderService.js:6:32%0Ahttps:%2F%2Fserify.org%2FEventHandler.js:25:51%0A%5Bnative%20code%5D%0Ainstantiate@https:%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.5.8%2Fangular.min.js:42:96%0Ac@https:%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.5.8%2Fangular.min.js:39:41%0Ad@https:%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.5.8%2Fangular.min.js:39:423%0Ahttps:%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.5.8%2Fangular.min.js:40:2%0Aq@https:%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.5.8%2Fangular.min.js:7:359%0Ag@https:%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.5.8%2Fangular.min.js:39:320%0Acb@https:%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.5.8%2Fangular.min.js:43:337%0Ac@https:%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.5.8%2Fangular.min.js:20:392%0Ahttps:%2F%2Fserify.org%2Findex.js:215:19%0Ab@https:%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.5.8%2Fangular.min.js:189:488%0ASf@https:%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.5.8%2Fangular.min.js:37:131%0Ad@https:%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.5.8%2Fangular.min.js:37:75

The message says: 
```Failed to instantiate module MainApp due to:
The quota has been exceeded.
setItem@[native code]
Save@https://serify.org/StorageProviderService.js:6:32
https://serify.org/EventHandler.js:25:51
[native code]
instantiate@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:42:96
c@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:39:41
d@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:39:423
https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:40:2
q@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:7:359
g@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:39:320
cb@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:43:337
c@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:20:392
https://serify.org/index.js:215:19
b@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:189:488
Sf@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:37:131
d@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:37:75
