### ISSUE TITLE
Create reusable navbar and footer

### ISSUE THREAD

**Issue by wparad** [serify-health/website#32]
We have separate navbars and footer per screen, they really should be the same across all of them.  There is one exception we'll have to deal with, which is that on the main page there is a link to the public profile, we might want to move that into the form.

**Comment by HenryHins** [comment]
...been working on this. I created a controller for the navigation bar. However I had troubles allowing the navigation controller to communicate with the other controllers (mainly `ng-show`). I got it kinda working using `$rootScope`, but I'm not sure if it is the best practice. Any thought on this?

**Comment by wparad** [comment]
I figured this may be complicated from a functional standpoint.  `$rootScope` may be the right thing for executing the login, but the storage of the result to pass to the rest of the view probably belongs in what is called a `service`.  I think there are some examples of them, although they are also a good place to pass data around.

How about this, want to put a PR, and then I may use your commits to finish the work, or is that enough of a suggestion and you want to try to take it a bit further?
