### ISSUE TITLE
Cannot Copy and Paste

### ISSUE THREAD

**Issue by wparad** [serify-health/website#39]
The website does not allow copying and pasting, can that be enabled?

**Comment by HenryHins** [comment]
Ha I thought it was intentional?

In the `Index.CSS` file, it was written

```
-webkit-user-select: none;		/* prevent copy paste, to allow, change 'none' to 'text' */
```

I will make a PR.

**Comment by wparad** [comment]
More like accident.  It was a copy and paste issue when setting up the file initially, most of that was just templated in.
